# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_file',
            field=models.FileField(blank=True, upload_to='joe'),
        ),
    ]
