# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20171002_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_file',
            field=models.FileField(blank=True, upload_to=posts.models.user_directory_path),
        ),
    ]
